apiVersion: apps/v1
kind: Deployment
metadata:
  name: chihesd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chihesd
  template:
    metadata:
      labels:
        app: chihesd
    spec:
      containers:
      - image: okteto.dev/chihesd:latest
        name: chihesd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www4.watchserieshd.tv"
        - name: Vless_UUID
          value: "5ee669c6-3d90-43f6-bd36-cd08dcef9294"
        - name: Vless_Path
          value: "/rtyiuwef"
        - name: Vmess_UUID
          value: "5ee669c6-3d90-43f6-bd36-cd08dcef9294"
        - name: Vmess_Path
          value: "/Suyr4ers"
        - name: Share_Path
          value: "/Share402"
