apiVersion: apps/v1
kind: Deployment
metadata:
  name: okiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okiler
  template:
    metadata:
      labels:
        app: okiler
    spec:
      containers:
      - image: okteto.dev/okiler:latest
        name: okiler
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "onlinemovieshindi.com"
        - name: Vless_UUID
          value: "6c7eb994-ef0d-415d-8866-9d2ca0d2b9ba"
        - name: Vless_Path
          value: "/tmoeurn"
        - name: Vmess_UUID
          value: "6c7eb994-ef0d-415d-8866-9d2ca0d2b9ba"
        - name: Vmess_Path
          value: "/aihuy6td"
        - name: Share_Path
          value: "/Share322"
