apiVersion: apps/v1
kind: Deployment
metadata:
  name: treczyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treczyk
  template:
    metadata:
      labels:
        app: treczyk
    spec:
      containers:
      - image: okteto.dev/treczyk:latest
        name: treczyk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animefrenzy.net"
        - name: Vless_UUID
          value: "1a1569b3-9545-414f-b92c-f0ef73909427"
        - name: Vless_Path
          value: "/yjutwsd"
        - name: Vmess_UUID
          value: "1a1569b3-9545-414f-b92c-f0ef73909427"
        - name: Vmess_Path
          value: "/PWTEH5R"
        - name: Share_Path
          value: "/Share435"
