apiVersion: apps/v1
kind: Deployment
metadata:
  name: lictaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lictaw
  template:
    metadata:
      labels:
        app: lictaw
    spec:
      containers:
      - image: okteto.dev/lictaw:latest
        name: lictaw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "2530dd5d-f002-404d-8df5-f7114ecd18ec"
        - name: Vless_Path
          value: "/g3rtujh"
        - name: Vmess_UUID
          value: "2530dd5d-f002-404d-8df5-f7114ecd18ec"
        - name: Vmess_Path
          value: "/sfn34rtgv"
        - name: Share_Path
          value: "/Share659"
