apiVersion: apps/v1
kind: Deployment
metadata:
  name: hchile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hchile
  template:
    metadata:
      labels:
        app: hchile
    spec:
      containers:
      - image: okteto.dev/hchile:latest
        name: hchile
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.freemusicarchive.org"
        - name: Vless_UUID
          value: "9a93056a-5cbd-456e-8aae-98ca9ecb550b"
        - name: Vless_Path
          value: "/beoplyAS5"
        - name: Vmess_UUID
          value: "9a93056a-5cbd-456e-8aae-98ca9ecb550b"
        - name: Vmess_Path
          value: "/jx7uwsdiy"
        - name: Share_Path
          value: "/Share051"
