apiVersion: v1
kind: Service
metadata:
  name: treczyk
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "treczyk"
    port: 8080
  selector:
    app: treczyk
